// Subconjunto curado del wordlist BIP39 en espanol
// 256 palabras comunes, faciles de escribir y sin ambiguedad
export const WORDLIST_ES = [
  'abeja', 'abril', 'actor', 'agua', 'album', 'aldea', 'alfa', 'algo',
  'alma', 'alto', 'amigo', 'angel', 'ancho', 'anillo', 'arena', 'arbol',
  'arco', 'arma', 'arte', 'atlas', 'ave', 'azul', 'bahia', 'baile',
  'banco', 'barco', 'bello', 'beso', 'bicho', 'blanco', 'boda', 'bolsa',
  'bomba', 'borde', 'bravo', 'brisa', 'burro', 'buscar', 'cabo', 'caer',
  'cafe', 'calma', 'cama', 'campo', 'canal', 'canto', 'carne', 'carta',
  'casa', 'casco', 'causa', 'cebra', 'cerdo', 'cero', 'chico', 'cielo',
  'cinco', 'circo', 'claro', 'clave', 'clima', 'cobra', 'coche', 'cofre',
  'color', 'conde', 'coral', 'corte', 'crear', 'crudo', 'cubo', 'cueva',
  'cumbre', 'curso', 'danza', 'delta', 'dicha', 'disco', 'docil', 'donde',
  'donar', 'dorso', 'drama', 'ducha', 'dulce', 'duque', 'eco', 'edad',
  'elfo', 'elite', 'enero', 'envio', 'epoca', 'erizo', 'escudo', 'espejo',
  'fable', 'falda', 'faro', 'feliz', 'feria', 'fibra', 'fiera', 'finca',
  'firma', 'flaco', 'flecha', 'flora', 'fonda', 'forma', 'fresa', 'fruta',
  'fuego', 'fuente', 'gafas', 'gallo', 'gamba', 'genio', 'globo', 'golpe',
  'gorra', 'gota', 'grupo', 'guapo', 'guia', 'gusano', 'halcon', 'hambre',
  'harina', 'hielo', 'hierro', 'higo', 'hoja', 'hongo', 'hueco', 'humo',
  'ideal', 'igloo', 'indio', 'isla', 'jabon', 'jardin', 'joven', 'juego',
  'jugo', 'julio', 'junco', 'justo', 'labio', 'lago', 'lanza', 'largo',
  'lavar', 'lemon', 'lento', 'leon', 'libro', 'limon', 'lince', 'lino',
  'lobo', 'loco', 'lona', 'lucir', 'lugar', 'luna', 'madre', 'mango',
  'manto', 'marca', 'marea', 'mesa', 'metro', 'miel', 'mina', 'moda',
  'monte', 'monje', 'moral', 'muela', 'mundo', 'muro', 'nadar', 'nave',
  'nieve', 'noble', 'noche', 'norte', 'novio', 'nube', 'nueve', 'nuez',
  'obispo', 'ocaso', 'oliva', 'opera', 'orden', 'orilla', 'padre', 'palma',
  'panda', 'papel', 'pared', 'parte', 'pasto', 'perla', 'piano', 'piedra',
  'plata', 'plaza', 'pluma', 'poeta', 'polvo', 'prado', 'pulso', 'punto',
  'queso', 'rama', 'rana', 'raton', 'rayo', 'reina', 'reloj', 'rio',
  'roca', 'ronda', 'ropa', 'rosa', 'rueda', 'rumbo', 'sabor', 'salir',
  'salto', 'selva', 'seria', 'siglo', 'silla', 'sirena', 'solar', 'sombra',
  'soplo', 'suave', 'suelo', 'tabla', 'tango', 'techo', 'tigre', 'torre',
  'trigo', 'trueno', 'tumba', 'unico', 'valle', 'vapor', 'verde', 'viaje',
]
